### PR TITLE
Local Testing Instructions

### PR DESCRIPTION
**Pull request by lloyd094**
Added instructions to explain how to test on a local machine without a pre-existing web server.

### CODE REVIEW

**Comment by hang-up** [comment]
If you run `npm run dev`, it will open up a local server on `localhost:8000` ;)

Maybe something along these lines would be better?


> Viewing the content outputted in `dist` requires a web server:
> ```
> npm install local-web-server -g
> cd dist
> ws
> ```

What do you think?

**Comment by lloyd094** [comment]
Ohoh! Did not know that's what dev did! Awesome!

And yes, the wording you have is good. Need me to make the changes?

**Comment by hang-up** [comment]
Please do :D !

**Comment by hang-up** [comment]
Thanks!

**Pull request merged**
